### PR TITLE
rework fishing

### PR DESCRIPTION
**Pull request by StojanovicMilos**
- add new fishing - almost perfect - should have perfect score in 19/20 cases, miss or have bad score in 1/20 cases. This was requested for endgame fishing so that fish that can kill player doesn't spawn.
- reduce duplication by extracting common methods
- refactor code to use async await instead of then
- use await promise instead of settimeout to be able to change delay dynamically for almost perfect fishing
- reorganize file based on uncle bob's suggestion: public methods first, private methods are defined in order of usage

### CODE REVIEW

**Comment by paccao** [comment]
I tested your implementation out and I wonder if it's possible to make it do 4 100% perfect runs then do 1 run with ~9500 score like you have implemented and then repeat that process. That would make fishing at the last spot even more efficient.

**Review by paccao — APPROVED** [review]

**Comment by StojanovicMilos** [comment]
@paccao thanks for the kind words. Yes, what you suggested is more than doable, but @ArgentumHeart said he did not see this as a rework for fishing, so I don't think he will accept this PR. Maybe if two of us ask him nicely... :)

**Comment by paccao** [comment]
Its not a rework, but I think its a good addition nonetheless, change title and he won't notice.. :D

**Comment by ArgentumHeart** [comment]
Closing since 0.7.0 will allow userdefined interval for pixelscan.

**Pull request closed without merging**
